insert into bookmarks (id, title, link, descrip, rating)
    values
    ('3cbfeda0-56a5-48e2-a0ad-51a0026e7972', 'Facebook for Developers', 'https://developers.facebook.com/', 'Facebook for Developers empowers developers and businesses to build for the future. Join a community of developers, attend meetups, and collaborate online.', 2),
    ('cf5598ea-d43a-4a20-bc56-f881cea77049', 'Cooking Measurements Converter', 'https://www.convert-me.com/en/convert/cooking/', 'This page helps you easily convert units from your recipe: grams to milliliters, liters to ounces, tablespoons to grams, and more.', -1),
    ('c06333ae-ea4f-4efc-afa9-2831064b5bb0', 'Online UUID Generator', 'http://https://www.uuidgenerator.net/', 'The UUIDs generated by this site are provided AS IS...', 3),
    ('896a333c-c91a-4f62-a5bb-6eb88e2b012f', 'Kobold Fight Club', 'http://kobold.club/fight/#/encounter-builder', '', 5), 
    ('cc0819b0-cd76-41fd-af84-da7a0127dabf', 'BuzzSumo', 'https://buzzsumo.com/', '', 5),
    ('37015e0c-60ce-48f0-9bf2-aaf0612fc12a', 'Melissa Meier Art', 'http://www.melissameierart.com/', 'Melissa Meier''s work confronts social and spiritual issues by incorporating mixed media sculpture into narrative assemblage.', 4),
    ('4b3c4d69-595a-4995-b6fc-5b84173a25b6', 'How to Escape Single Quotes in SQL', 'https://www.databasestar.com/sql-escape-single-quote/', '', -1),
    ('2577a4cb-992d-4c55-93bb-537544b7bd0f', 'Bojack Horsement Designer Lisa Hanawalt Talks to Cartoonist Kate Beaton', 'https://themuse.jezebel.com/bojack-horseman-designer-lisa-hanawalt-talks-to-cartoon-1731476602', 'I was thrilled to catch up with Kate and talk about her new book Step Aside ...', 2),
    ('d7c8ccd6-0f45-4db5-91ce-2fd985877822', 'Tech Resources | Magento', 'https://magento.com/technical-resources', 'Everything you need to build and manage a customized Magento storefront.', 1), 
    ('2cf4adf8-8ae0-41ef-a790-72dd08d33681', 'Landmarks You Should Know', 'http://sevencamels.blogspot.com/2016/06/landmarks-you-should-know.html', 'Here are a couple of useful pages from Andrew Loomis'' book "Figure Drawing For All It''s Worth" that show exactly which landmarks can be seen on the surface of the human figure.', 5); 
